# Generated by Django 5.1.5 on 2025-01-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='phone',
            field=models.BigIntegerField(max_length=30),
        ),
    ]
